CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,1)
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 4
PRINT_FREQ: 10

DATASET:
  DATASET: cocostuff
  ROOT: data/
  TEST_SET: 'list/cocostuff/test.lst'
  TRAIN_SET: 'list/cocostuff/train.lst'
  NUM_CLASSES: 171
MODEL:
  NAME: pidnet_large_uniPag128_dappm112_dfm3_coco256_s2
  NUM_OUTPUTS: 2
  PRETRAINED: "pretrained_models/imagenet/PIDNet_L_imagenet.pth.tar"
  ALIGN_CORNERS: false
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
TRAIN:
  IMAGE_SIZE:
  - 640
  - 640
  BASE_SIZE: 640
  BATCH_SIZE_PER_GPU: 8
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 180
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.005
  WD: 0.0001
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  DOWNSAMPLERATE: 1
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16
TEST:
  IMAGE_SIZE:
  - 640
  - 640
  BASE_SIZE: 640
  BATCH_SIZE_PER_GPU: 8
  FLIP_TEST: false
  MULTI_SCALE: false
  MODEL_FILE: ''
  OUTPUT_INDEX: 1
